// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TMS_Project.DataLayer.Context;

#nullable disable

namespace TMS_Project.Migrations
{
    [DbContext(typeof(TmsDbContext))]
    [Migration("20231210044856_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TMS_Project.DataLayer.Model.Carrier", b =>
                {
                    b.Property<int>("CarrierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DepotCity")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("FtlRate")
                        .HasColumnType("double");

                    b.Property<int>("Ftla")
                        .HasColumnType("int");

                    b.Property<double>("LtlRate")
                        .HasColumnType("double");

                    b.Property<int>("Ltla")
                        .HasColumnType("int");

                    b.Property<double>("ReefCharge")
                        .HasColumnType("double");

                    b.HasKey("CarrierId");

                    b.ToTable("Carrier", (string)null);
                });

            modelBuilder.Entity("TMS_Project.DataLayer.Model.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CityId");

                    b.ToTable("City", (string)null);
                });

            modelBuilder.Entity("TMS_Project.DataLayer.Model.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("TMS_Project.DataLayer.Model.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Amount")
                        .HasColumnType("double");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("RateId")
                        .HasColumnType("int");

                    b.HasKey("InvoiceId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("RateId");

                    b.ToTable("Invoice", (string)null);
                });

            modelBuilder.Entity("TMS_Project.DataLayer.Model.LogFile", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("LogDetails")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LogTimeStamp")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LogId");

                    b.HasIndex("UserId");

                    b.ToTable("LogFile", (string)null);
                });

            modelBuilder.Entity("TMS_Project.DataLayer.Model.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateCompleted")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateInitiated")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DestinationCityId")
                        .HasColumnType("int");

                    b.Property<int?>("JobType")
                        .HasColumnType("int");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<double>("Quantity")
                        .HasColumnType("double");

                    b.Property<int>("SourceCityId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VanType")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DestinationCityId");

                    b.HasIndex("SourceCityId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("TMS_Project.DataLayer.Model.Rate", b =>
                {
                    b.Property<int>("RateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Amount")
                        .HasColumnType("double");

                    b.Property<int>("RateType")
                        .HasColumnType("int");

                    b.HasKey("RateId");

                    b.ToTable("Rate", (string)null);
                });

            modelBuilder.Entity("TMS_Project.DataLayer.Model.Route", b =>
                {
                    b.Property<int>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DestinationCityId")
                        .HasColumnType("int");

                    b.Property<double>("Distance")
                        .HasColumnType("double");

                    b.Property<double>("Duration")
                        .HasColumnType("double");

                    b.Property<int>("SourceCityId")
                        .HasColumnType("int");

                    b.HasKey("RouteId");

                    b.HasIndex("DestinationCityId");

                    b.HasIndex("SourceCityId");

                    b.ToTable("Route", (string)null);
                });

            modelBuilder.Entity("TMS_Project.DataLayer.Model.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CarrierId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("TripStatus")
                        .HasColumnType("int");

                    b.HasKey("TripId");

                    b.HasIndex("CarrierId");

                    b.HasIndex("OrderId");

                    b.ToTable("Trip", (string)null);
                });

            modelBuilder.Entity("TMS_Project.DataLayer.Model.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("TMS_Project.DataLayer.Model.Invoice", b =>
                {
                    b.HasOne("TMS_Project.DataLayer.Model.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TMS_Project.DataLayer.Model.Order", "Order")
                        .WithOne("Invoices")
                        .HasForeignKey("TMS_Project.DataLayer.Model.Invoice", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TMS_Project.DataLayer.Model.Rate", "Rates")
                        .WithMany("Invoices")
                        .HasForeignKey("RateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Order");

                    b.Navigation("Rates");
                });

            modelBuilder.Entity("TMS_Project.DataLayer.Model.LogFile", b =>
                {
                    b.HasOne("TMS_Project.DataLayer.Model.User", "Users")
                        .WithMany("LogFiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TMS_Project.DataLayer.Model.Order", b =>
                {
                    b.HasOne("TMS_Project.DataLayer.Model.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TMS_Project.DataLayer.Model.City", "DestinationCity")
                        .WithMany("DestinationOrders")
                        .HasForeignKey("DestinationCityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TMS_Project.DataLayer.Model.City", "SourceCity")
                        .WithMany("SourceOrders")
                        .HasForeignKey("SourceCityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TMS_Project.DataLayer.Model.User", null)
                        .WithMany("Orders")
                        .HasForeignKey("UserId");

                    b.Navigation("Customer");

                    b.Navigation("DestinationCity");

                    b.Navigation("SourceCity");
                });

            modelBuilder.Entity("TMS_Project.DataLayer.Model.Route", b =>
                {
                    b.HasOne("TMS_Project.DataLayer.Model.City", "DestinationCity")
                        .WithMany("DestinationRoutes")
                        .HasForeignKey("DestinationCityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TMS_Project.DataLayer.Model.City", "SourceCity")
                        .WithMany("SourceRoutes")
                        .HasForeignKey("SourceCityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DestinationCity");

                    b.Navigation("SourceCity");
                });

            modelBuilder.Entity("TMS_Project.DataLayer.Model.Trip", b =>
                {
                    b.HasOne("TMS_Project.DataLayer.Model.Carrier", "Carrier")
                        .WithMany("Trips")
                        .HasForeignKey("CarrierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TMS_Project.DataLayer.Model.Order", "Order")
                        .WithMany("Trips")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrier");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("TMS_Project.DataLayer.Model.Carrier", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("TMS_Project.DataLayer.Model.City", b =>
                {
                    b.Navigation("DestinationOrders");

                    b.Navigation("DestinationRoutes");

                    b.Navigation("SourceOrders");

                    b.Navigation("SourceRoutes");
                });

            modelBuilder.Entity("TMS_Project.DataLayer.Model.Customer", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("TMS_Project.DataLayer.Model.Order", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("TMS_Project.DataLayer.Model.Rate", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("TMS_Project.DataLayer.Model.User", b =>
                {
                    b.Navigation("LogFiles");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
